---
- name: Setup Vector Ubuntu
  block:
  - name: Install vector deb
    become: true
    ansible.builtin.apt:
      deb:  https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb
      update_cache: yes
      state: present
  - name: Vector | Template Config
    ansible.builtin.template:
      src: templates/vector.yml.j2
      dest: /etc/vector/vector.yaml
      mode: "0644"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"
      validate: vector validate --no-environment --config-yaml %s
  - name: Vector | Create systemd unit
    ansible.builtin.template:
      src: templates/vector.service.j2
      dest: /etc/systemd/vector.service
      mode: "0755"
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_gid }}"